プロフィール補足情報の表示サポート
cinderella-project/iMast pull request #205
Opened 2021-08-16 13:57 UTC by shibafu528

refs #175 

このPRでは、WebUI上でプロフィール補足情報と呼ばれている `account.fields` の表示を追加します。

SwiftおよびUIKitを使うのには慣れておらず見様見真似で書いたので、間違っている所などあったら教えてください。

## 詰めきれていない所

* verified_at が付いている項目に何か表示するべきか
  * WebUIでは ✅ が付き、セルの背景が緑色になる。nameかvalueいずれかの先頭に ✅ を置いてみるのは考えたが、やっていない。何か良案があれば。

## Screenshot

<img width="564" alt="スクリーンショット 2021-08-16 22 53 12" src="https://user-images.githubusercontent.com/1352154/129574759-c1a05b18-e12a-45f5-baf6-6f44873d3e25.png">

2021-08-16 14:47 UTC, rinsuki commented
よさそう！ちょっと最近は Boot Camp に浮気してごちゃごちゃやってるので、macOSに戻ってきたらちゃんと確認します。

> verified_at が付いている項目に何か表示するべきか 

nameの横に右寄せで `日付 ✔️` みたいなのを出すとかも良いかも。チェックマークは emoji じゃなくて SF Symbols 使ったほうが綺麗に出そう。どこからどこまでがそれかというのを分離するために文字色はlabelじゃないやつがよさそう。

認証日時の精度についてちょっと思ったこと:
- 横320ptだとたぶん時間入れるとnameが消しとんじゃうけど、iPadとかの横幅に余裕がある環境だと全部出てほしい気がする (iOS端末だとWebのtitleで日付見れないし)
- iMastは基本的に横320pt端末で使えるUIに落とす方向だけど、年月日と時間を出すUILabelを分けて、Auto Layout の priority を 年月日はrequired/時間は一番優先度低くみたいにするといいかもしれない。
  - AutoLayout の priority 回りは MastodonPostCellViewController が参考になるかもしれないけど普通にググったりしたほうが早いかも
  - もしくは使える幅によって精度をだんだん上げてく日時表示用UILabelを作ってもいいけど、ここでしか使わなさそうだしそこまで工数かけるものでもな…という感じ。
  - ところでローカライズ的に年月日と時間の表記って全てのロケールでぶった切って並べていいものなのか？まあでも iMast が対応してる言語内(CJK, English)だと問題はなさそうな気がする
  - とはいえどっちにもそこまで工数わざわざかけるのも微妙な気がしてきたので年月日だけでもいいかも。おまかせします。
- 表にはチェックマークだけ出してcellの3Dタッチでメニュー出して日時はそこで表示でもいいかもしれない？それなら普通に秒まで出しても大丈夫そう。
  - でもvalue内リンクの3Dタッチと被りそうな気もする

2021-08-18 02:08 UTC, rinsuki requested changes

2021-08-18 02:08 UTC, rinsuki commented on Sources/iOS/App/CustomViews/UserProfile/UserProfileTopViewController.swift
> +            fields.indices.forEach { index in
中身が一行で済むわけじゃない場合は forEach じゃなくて for-in のほうを使いたいです。
```suggestion
            for index in fields.indices {
```

2021-08-18 02:08 UTC, rinsuki commented on Sources/iOS/App/CustomViews/UserProfile/UserProfileFieldViewController.swift
> +        v.textColor = v.tintColor
Mastodonでも書いたけど、ここはtintColorじゃなくて `UIColor.systemGreen` とかでもいいかもしれない

2021-08-19 00:56 UTC, shibafu528 commented on Sources/iOS/App/CustomViews/UserProfile/UserProfileFieldViewController.swift
> +        v.textColor = v.tintColor
試してみます

2021-08-19 13:36 UTC, shibafu528 commented on Sources/iOS/App/CustomViews/UserProfile/UserProfileFieldViewController.swift
> +        v.textColor = v.tintColor
普段使ってるディスプレイだとこれ文字に使って大丈夫なのかなという気持ちがあったんですが、iPod touchの実機で見たら全然問題なさそうなのでsystemGreenにします。

2021-08-19 16:58 UTC, rinsuki approved these changes

2021-08-19 16:58 UTC, merged